[wokwi]
version = 1
elf = "carbontrace-iot/build/esp32.esp32.esp32doit-devkit-v1/carbontrace-iot.ino.elf"
firmware = "carbontrace-iot/build/esp32.esp32.esp32doit-devkit-v1/carbontrace-iot.ino.bin"

[[wifi]]
ssid = "Wokwi-GUEST"
password = ""
internet = true
channel = 6

[[net.forward]]
from = "0.0.0.0:8180"
to = "target:80"